nuget:
  account_feed: true

init:
  - git config --global core.autocrlf true

branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/

build_script:
  - build.cmd --quiet verify

after_build:
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

artifacts: 
 - path: '**\Microsoft.AspNetCore.Authentication.ActiveDirectory*.nupkg' 

clone_depth: 1

test: off

deploy:
  provider: NuGet
  api_key:
    secure: 3Riwgut3XJ2XobdaMb7/phU0SNVj/SwDfkY6F0TSqXsnpcdIzZc+s+yK/XjHu+8L
  skip_symbols: false