nuget:
  account_feed: true

init:
  - git config --global core.autocrlf true

install:
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
 - ps: dnvm update-self
 - ps: dnvm upgrade
 - ps: dnvm install 1.0.0-rc1-update1
 - ps: dnvm list
 - ps: dnvm use 1.0.0-rc1-update1

before_build:
 - ps: dnu restore

after_build:
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

artifacts: 
 - path: '**\Microsoft.AspNetCore.Authentication.ActiveDirectory*.nupkg' 

deploy:
  provider: NuGet
  api_key:
    secure: 3Riwgut3XJ2XobdaMb7/phU0SNVj/SwDfkY6F0TSqXsnpcdIzZc+s+yK/XjHu+8L
  skip_symbols: false